const categories = [
  {
    link: "/posts",
    section: "posts",
    icon: <i className="bx bx-news"></i>,
    text: "Kế toán / Kiểm toán",
    slug: "ke-toan",
  },
  {
    link: "/orders",
    section: "orders",
    icon: <i className="bx bx-receipt"></i>,
    text: "Quảng cáo/ Khuyến mãi / Đối ngoại",
    slug: "ke-toan",
  },
  {
    link: "/customers",
    section: "customers",
    icon: <i className="bx bx-user"></i>,
    text: "Nông nghiệp / Lâm nghiệp",
    slug: "ke-toan",
  },
  {
    link: "/stats",
    section: "stats",
    icon: <i className="bx bx-line-chart"></i>,
    text: "Nghệ thuật/ thiết kế / Giải trí",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Ngân hàng / chứng khoán",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thư ký/ Hành chính",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Tư vấn",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  },
  {
    link: "/settings",
    section: "settings",
    icon: <i className="bx bx-cog"></i>,
    text: "Thêm",
    slug: "ke-toan",
  }
];

export default categories;
