const province = [
  {
    name: "Hà Nội",
    label: "Hà Nội",
    value: "ha-noi",
    slug: "ha-noi",
    type: "thanh-pho",
    name_with_type: "Thành phố Hà Nội",
    code: "01",
  },
  {
    name: "Hà Giang",
    label: "Hà Giang",
    value: "ha-giang",
    slug: "ha-giang",
    type: "tinh",
    name_with_type: "Tỉnh Hà Giang",
    code: "02",
  },
  {
    name: "Cao Bằng",
    label: "Cao Bằng",
    value: "cao-bang",
    slug: "cao-bang",
    type: "tinh",
    name_with_type: "Tỉnh Cao Bằng",
    code: "04",
  },
  {
    name: "Bắc Kạn",
    label: "Bắc Kạn",
    value: "bac-kan",
    slug: "bac-kan",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Kạn",
    code: "06",
  },
  {
    name: "Tuyên Quang",
    label: "Tuyên Quang",
    value: "tuyen-quang",
    slug: "tuyen-quang",
    type: "tinh",
    name_with_type: "Tỉnh Tuyên Quang",
    code: "08",
  },
  {
    name: "Lào Cai",
    label: "Lào Cai",
    value: "lao-cai",
    slug: "lao-cai",
    type: "tinh",
    name_with_type: "Tỉnh Lào Cai",
    code: "10",
  },
  {
    name: "Điện Biên",
    label: "Điện Biên",
    value: "dien-bien",
    slug: "dien-bien",
    type: "tinh",
    name_with_type: "Tỉnh Điện Biên",
    code: "11",
  },
  {
    name: "Lai Châu",
    label: "Lai Châu",
    value: "lai-chau",
    slug: "lai-chau",
    type: "tinh",
    name_with_type: "Tỉnh Lai Châu",
    code: "12",
  },
  {
    name: "Sơn La",
    label: "Sơn La",
    value: "son-la",
    slug: "son-la",
    type: "tinh",
    name_with_type: "Tỉnh Sơn La",
    code: "14",
  },
  {
    name: "Yên Bái",
    label: "Yên Bái",
    value: "yen-bai",
    slug: "yen-bai",
    type: "tinh",
    name_with_type: "Tỉnh Yên Bái",
    code: "15",
  },
  {
    name: "Hoà Bình",
    label: "Hoà Bình",
    value: "hoa-binh",
    slug: "hoa-binh",
    type: "tinh",
    name_with_type: "Tỉnh Hoà Bình",
    code: "17",
  },
  {
    name: "Thái Nguyên",
    label: "Thái Nguyên",
    value: "thai-nguyen",
    slug: "thai-nguyen",
    type: "tinh",
    name_with_type: "Tỉnh Thái Nguyên",
    code: "19",
  },
  {
    name: "Lạng Sơn",
    label: "Lạng Sơn",
    value: "lang-son",
    slug: "lang-son",
    type: "tinh",
    name_with_type: "Tỉnh Lạng Sơn",
    code: "20",
  },
  {
    name: "Quảng Ninh",
    label: "Quảng Ninh",
    value: "quang-ninh",
    slug: "quang-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Ninh",
    code: "22",
  },
  {
    name: "Bắc Giang",
    label: "Bắc Giang",
    value: "bac-giang",
    slug: "bac-giang",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Giang",
    code: "24",
  },
  {
    name: "Phú Thọ",
    label: "Phú Thọ",
    value: "phu-tho",
    slug: "phu-tho",
    type: "tinh",
    name_with_type: "Tỉnh Phú Thọ",
    code: "25",
  },
  {
    name: "Vĩnh Phúc",
    label: "Vĩnh Phúc",
    value: "vinh-phuc",
    slug: "vinh-phuc",
    type: "tinh",
    name_with_type: "Tỉnh Vĩnh Phúc",
    code: "26",
  },
  {
    name: "Bắc Ninh",
    label: "Bắc Ninh",
    value: "bac-ninh",
    slug: "bac-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Ninh",
    code: "27",
  },
  {
    name: "Hải Dương",
    label: "Hải Dương",
    value: "hai-duong",
    slug: "hai-duong",
    type: "tinh",
    name_with_type: "Tỉnh Hải Dương",
    code: "30",
  },
  {
    name: "Hải Phòng",
    label: "Hải Phòng",
    value: "hai-phong",
    slug: "hai-phong",
    type: "thanh-pho",
    name_with_type: "Thành phố Hải Phòng",
    code: "31",
  },
  {
    name: "Hưng Yên",
    label: "Hưng Yên",
    value: "hung-yen",
    slug: "hung-yen",
    type: "tinh",
    name_with_type: "Tỉnh Hưng Yên",
    code: "33",
  },
  {
    name: "Thái Bình",
    label: "Thái Bình",
    value: "thai-binh",
    slug: "thai-binh",
    type: "tinh",
    name_with_type: "Tỉnh Thái Bình",
    code: "34",
  },
  {
    name: "Hà Nam",
    label: "Hà Nam",
    value: "ha-nam",
    slug: "ha-nam",
    type: "tinh",
    name_with_type: "Tỉnh Hà Nam",
    code: "35",
  },
  {
    name: "Nam Định",
    label: "Nam Định",
    value: "nam-dinh",
    slug: "nam-dinh",
    type: "tinh",
    name_with_type: "Tỉnh Nam Định",
    code: "36",
  },
  {
    name: "Ninh Bình",
    label: "Ninh Bình",
    value: "ninh-binh",
    slug: "ninh-binh",
    type: "tinh",
    name_with_type: "Tỉnh Ninh Bình",
    code: "37",
  },
  {
    name: "Thanh Hóa",
    label: "Thanh Hóa",
    value: "thanh-hoa",
    slug: "thanh-hoa",
    type: "tinh",
    name_with_type: "Tỉnh Thanh Hóa",
    code: "38",
  },
  {
    name: "Nghệ An",
    label: "Nghệ An",
    value: "nghe-an",
    slug: "nghe-an",
    type: "tinh",
    name_with_type: "Tỉnh Nghệ An",
    code: "40",
  },
  {
    name: "Hà Tĩnh",
    label: "Hà Tĩnh",
    value: "ha-tinh",
    slug: "ha-tinh",
    type: "tinh",
    name_with_type: "Tỉnh Hà Tĩnh",
    code: "42",
  },
  {
    name: "Quảng Bình",
    label: "Quảng Bình",
    value: "quang-binh",
    slug: "quang-binh",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Bình",
    code: "44",
  },
  {
    name: "Quảng Trị",
    label: "Quảng Trị",
    value: "quang-tri",
    slug: "quang-tri",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Trị",
    code: "45",
  },
  {
    name: "Thừa Thiên Huế",
    label: "Thừa Thiên Huế",
    value: "thua-thien-hue",
    slug: "thua-thien-hue",
    type: "tinh",
    name_with_type: "Tỉnh Thừa Thiên Huế",
    code: "46",
  },
  {
    name: "Đà Nẵng",
    label: "Đà Nẵng",
    value: "da-nang",
    slug: "da-nang",
    type: "thanh-pho",
    name_with_type: "Thành phố Đà Nẵng",
    code: "48",
  },
  {
    name: "Quảng Nam",
    label: "Quảng Nam",
    value: "quang-nam",
    slug: "quang-nam",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Nam",
    code: "49",
  },
  {
    name: "Quảng Ngãi",
    label: "Quảng Ngãi",
    value: "quang-ngai",
    slug: "quang-ngai",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Ngãi",
    code: "51",
  },
  {
    name: "Bình Định",
    label: "Bình Định",
    value: "binh-dinh",
    slug: "binh-dinh",
    type: "tinh",
    name_with_type: "Tỉnh Bình Định",
    code: "52",
  },
  {
    name: "Phú Yên",
    label: "Phú Yên",
    value: "phu-yen",
    slug: "phu-yen",
    type: "tinh",
    name_with_type: "Tỉnh Phú Yên",
    code: "54",
  },
  {
    name: "Khánh Hòa",
    label: "Khánh Hòa",
    value: "khanh-hoa",
    slug: "khanh-hoa",
    type: "tinh",
    name_with_type: "Tỉnh Khánh Hòa",
    code: "56",
  },
  {
    name: "Ninh Thuận",
    label: "Ninh Thuận",
    value: "ninh-thuan",
    slug: "ninh-thuan",
    type: "tinh",
    name_with_type: "Tỉnh Ninh Thuận",
    code: "58",
  },
  {
    name: "Bình Thuận",
    label: "Bình Thuận",
    value: "binh-thuan",
    slug: "binh-thuan",
    type: "tinh",
    name_with_type: "Tỉnh Bình Thuận",
    code: "60",
  },
  {
    name: "Kon Tum",
    label: "Kon Tum",
    value: "kon-tum",
    slug: "kon-tum",
    type: "tinh",
    name_with_type: "Tỉnh Kon Tum",
    code: "62",
  },
  {
    name: "Gia Lai",
    label: "Gia Lai",
    value: "gia-lai",
    slug: "gia-lai",
    type: "tinh",
    name_with_type: "Tỉnh Gia Lai",
    code: "64",
  },
  {
    name: "Đắk Lắk",
    label: "Đắk Lắk",
    value: "dak-lak",
    slug: "dak-lak",
    type: "tinh",
    name_with_type: "Tỉnh Đắk Lắk",
    code: "66",
  },
  {
    name: "Đắk Nông",
    label: "Đắk Nông",
    value: "dak-nong",
    slug: "dak-nong",
    type: "tinh",
    name_with_type: "Tỉnh Đắk Nông",
    code: "67",
  },
  {
    name: "Lâm Đồng",
    label: "Lâm Đồng",
    value: "lam-dong",
    slug: "lam-dong",
    type: "tinh",
    name_with_type: "Tỉnh Lâm Đồng",
    code: "68",
  },
  {
    name: "Bình Phước",
    label: "Bình Phước",
    value: "binh-phuoc",
    slug: "binh-phuoc",
    type: "tinh",
    name_with_type: "Tỉnh Bình Phước",
    code: "70",
  },
  {
    name: "Tây Ninh",
    label: "Tây Ninh",
    value: "tay-ninh",
    slug: "tay-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Tây Ninh",
    code: "72",
  },
  {
    name: "Bình Dương",
    label: "Bình Dương",
    value: "binh-duong",
    slug: "binh-duong",
    type: "tinh",
    name_with_type: "Tỉnh Bình Dương",
    code: "74",
  },
  {
    name: "Đồng Nai",
    label: "Đồng Nai",
    value: "dong-nai",
    slug: "dong-nai",
    type: "tinh",
    name_with_type: "Tỉnh Đồng Nai",
    code: "75",
  },
  {
    name: "Bà Rịa - Vũng Tàu",
    label: "Bà Rịa - Vũng Tàu",
    value: "ba-ria-vung-tau",
    slug: "ba-ria-vung-tau",
    type: "tinh",
    name_with_type: "Tỉnh Bà Rịa - Vũng Tàu",
    code: "77",
  },
  {
    name: "Hồ Chí Minh",
    label: "Hồ Chí Minh",
    value: "ho-chi-minh",
    slug: "ho-chi-minh",
    type: "thanh-pho",
    name_with_type: "Thành phố Hồ Chí Minh",
    code: "79",
  },
  {
    name: "Long An",
    label: "Long An",
    value: "long-an",
    slug: "long-an",
    type: "tinh",
    name_with_type: "Tỉnh Long An",
    code: "80",
  },
  {
    name: "Tiền Giang",
    label: "Tiền Giang",
    value: "tien-giang",
    slug: "tien-giang",
    type: "tinh",
    name_with_type: "Tỉnh Tiền Giang",
    code: "82",
  },
  {
    name: "Bến Tre",
    label: "Bến Tre",
    value: "ben-tre",
    slug: "ben-tre",
    type: "tinh",
    name_with_type: "Tỉnh Bến Tre",
    code: "83",
  },
  {
    name: "Trà Vinh",
    label: "Trà Vinh",
    value: "tra-vinh",
    slug: "tra-vinh",
    type: "tinh",
    name_with_type: "Tỉnh Trà Vinh",
    code: "84",
  },
  {
    name: "Vĩnh Long",
    label: "Vĩnh Long",
    value: "vinh-long",
    slug: "vinh-long",
    type: "tinh",
    name_with_type: "Tỉnh Vĩnh Long",
    code: "86",
  },
  {
    name: "Đồng Tháp",
    label: "Đồng Tháp",
    value: "dong-thap",
    slug: "dong-thap",
    type: "tinh",
    name_with_type: "Tỉnh Đồng Tháp",
    code: "87",
  },
  {
    name: "An Giang",
    label: "An Giang",
    value: "an-giang",
    slug: "an-giang",
    type: "tinh",
    name_with_type: "Tỉnh An Giang",
    code: "89",
  },
  {
    name: "Kiên Giang",
    label: "Kiên Giang",
    value: "kien-giang",
    slug: "kien-giang",
    type: "tinh",
    name_with_type: "Tỉnh Kiên Giang",
    code: "91",
  },
  {
    name: "Cần Thơ",
    label: "Cần Thơ",
    value: "can-tho",
    slug: "can-tho",
    type: "thanh-pho",
    name_with_type: "Thành phố Cần Thơ",
    code: "92",
  },
  {
    name: "Hậu Giang",
    label: "Hậu Giang",
    value: "hau-giang",
    slug: "hau-giang",
    type: "tinh",
    name_with_type: "Tỉnh Hậu Giang",
    code: "93",
  },
  {
    name: "Sóc Trăng",
    label: "Sóc Trăng",
    value: "soc-trang",
    slug: "soc-trang",
    type: "tinh",
    name_with_type: "Tỉnh Sóc Trăng",
    code: "94",
  },
  {
    name: "Bạc Liêu",
    label: "Bạc Liêu",
    value: "bac-lieu",
    slug: "bac-lieu",
    type: "tinh",
    name_with_type: "Tỉnh Bạc Liêu",
    code: "95",
  },
  {
    name: "Cà Mau",
    label: "Cà Mau",
    value: "ca-mau",
    slug: "ca-mau",
    type: "tinh",
    name_with_type: "Tỉnh Cà Mau",
    code: "96",
  },
];

export default province;
