SELECT * FROM job.fields;

INSERT INTO job.fields (id, name, typeField) 
VALUES(1 ,'Biên phiên dịch / Thông dịch viên', 'Bộ phân hổ trợ'),
( 2,'Nhân sự', 'Bộ phân hổ trợ'),
( 3,'Pháp lý / Luật', 'Bộ phân hổ trợ'),
( 4,'Thư ký / Hành Chính', 'Bộ phân hổ trợ'),
( 5,'An ninh / Bảo vệ', 'Dịch vụ'),
( 6,'Bán lẻ / Bán sỉ', 'Dịch vụ'),
( 7,'Chăm sóc sức khỏe / Y tế', 'Dịch vụ'),
( 8,'Dịch vụ khách hàng', 'Dịch vụ'),
( 9,'Giáo dục / Đào tạo / Thư viện', 'Dịch vụ'),
( 10,'Phi chính phủ / Phi lợi nhuận', 'Dịch vụ'),
(11 ,'Bảo hiểm', 'Dịch vụ tài chính'),
(12 ,'Kế toán / Kiểm toán', 'Dịch vụ tài chính'),
( 13,'Ngân hàng / Chứng khoán', 'Dịch vụ tài chính'),
( 14,'Tài chính / Đầu tư', 'Dịch vụ tài chính'),
(15 ,'Bán hàng / Kinh doanh', 'Dịch vụ khách hàng'),
( 16,'Hàng gia dụng', 'Dịch vụ khách hàng'),
( 17,'Quảng cáo / Đối ngoại', 'Dịch vụ khách hàng'),
( 18,'Thời trang', 'Dịch vụ khách hàng'),
( 19,'Tiếp thị', 'Dịch vụ khách hàng'),
( 20,'Tư vấn', 'Dịch vụ khách hàng'),
( 22,'Quản lý chất lượng', 'Hổ trợ sản xuất'),
( 23,'Vận chuyển / Giao hàng / Kho bãi', 'Hổ trợ sản xuất'),
( 24,'Vật tư / Thu mua', 'Hổ trợ sản xuất'),
( 25,'Xuất nhập khẩu / Ngoại thương', 'Hổ trợ sản xuất'),
( 26,'CNTT - Phần mềm', 'Công nghệ thông tin'),
( 27,'CNTT - Phần cứng / Mạng', 'Công nghệ thông tin'),
( 28,'Du lịch', 'Khách sạn / Du lịch'),
( 29,'Khách sạn', 'Khách sạn / Du lịch'),
( 30,'Nhà hàng / Dịch vụ ăn uống', 'Khách sạn / Du lịch'),
( 31,'Bảo trì / Sửa chữa', 'Kỹ thuật'),
( 32,'Điên lạnh / Nhiệt lạnh', 'Kỹ thuật'),
( 33,'Dược / Sinh học', 'Kỹ thuật'),
( 34,'Điện / Điện tử', 'Kỹ thuật'),
( 35,'Kỹ thuật ứng dụng / Cơ khí', 'Kỹ thuật'),
( 36,'Môi trường / Xử lý chất thải', 'Kỹ thuật'),
( 37,'An toàn lao động', 'Sản xuất'),
( 38,'Dầu khí / Khoáng sản', 'Sản xuất'),
( 39,'Dệt may / Da giày', 'Sản xuất'),
( 40,'Đồ gỗ', 'Sản xuất'),
( 41,'Hóa chất / Sinh hóa / Thực phẩm', 'Sản xuất'),
( 42,'Nông nghiệp / Lâm nghiệp', 'Sản xuất'),
( 43,'Ô tô', 'Sản xuất'),
( 44,'Sản xuất / Vận hành sản xuất', 'Sản xuất'),
( 45,'Thủy hải sản', 'Sản xuất'),
( 46,'Bất động sản', 'Xây dựng / Bất động sản'),
( 47,'Kiến trúc', 'Xây dựng / Bất động sản'),
( 48,'Nội thất / Ngoại thất', 'Xây dựng / Bất động sản'),
( 49,'Xây dựng', 'Xây dựng / Bất động sản'),
( 50,'Báo chí / Biên tập viên / Xuất bản', 'Truyền thông'),
( 51,'Nghệ thuật / Thiết kế', 'Truyền thông'),
( 52,'Viễn thông', 'Truyền thông'),
( 53,'Lao động phổ thông', 'Theo đối tượng'),
( 54,'Mới tốt nghiệp / Thực tập', 'Theo đối tượng'),
( 55,'Người nước ngoài', 'Theo đối tượng'),
( 56,'Quản lý điều hành', 'Theo đối tượng'),
( 57,'Khác', 'Khác');