INSERT INTO provinces (id , name, nameWithType ) VALUES(1,'Hà Nội', 'Thành phố Hà Nội'),
(2,'Hà Giang', 'Tỉnh Hà Giang'),
(4,'Cao Bằng', 'Tỉnh Cao Bằng'),
(6,'Bắc Kạn', 'Tỉnh Bắc Kạn'),
(8,'Tuyên Quang', 'Tỉnh Tuyên Quang'),
(10,'Lào Cai', 'Tỉnh Lào Cai'),
(11,'Điện Biên', 'Tỉnh Điện Biên'),
(12,'Lai Châu', 'Tỉnh Lai Châu'),
(14,'Sơn La', 'Tỉnh Sơn La'),
(15,'Yên Bái', 'Tỉnh Yên Bái'),
(17,'Hoà Bình', 'Tỉnh Hoà Bình'),
(19,'Thái Nguyên', 'Tỉnh Thái Nguyên'),
(20,'Lạng Sơn', 'Tỉnh Lạng Sơn'),
(22,'Quảng Ninh', 'Tỉnh Quảng Ninh'),
(24,'Bắc Giang', 'Tỉnh Bắc Giang'),
(25,'Phú Thọ', 'Tỉnh Phú Thọ'),
(26,'Vĩnh Phúc', 'Tỉnh Vĩnh Phúc'),
(27,'Bắc Ninh', 'Tỉnh Bắc Ninh'),
(30,'Hải Dương', 'Tỉnh Hải Dương'),
(31,'Hải Phòng', 'Thành phố Hải Phòng'),
(33,'Hưng Yên', 'Tỉnh Hưng Yên'),
(34,'Thái Bình', 'Tỉnh Thái Bình'),
(35,'Hà Nam', 'Tỉnh Hà Nam'),
(36,'Nam Định', 'Tỉnh Nam Định'),
(37,'Ninh Bình', 'Tỉnh Ninh Bình'),
(38,'Thanh Hóa', 'Tỉnh Thanh Hóa'),
(40,'Nghệ An', 'Tỉnh Nghệ An'),
(42,'Hà Tĩnh', 'Tỉnh Hà Tĩnh'),
(44,'Quảng Bình', 'Tỉnh Quảng Bình'),
(45,'Quảng Trị', 'Tỉnh Quảng Trị'),
(46,'Thừa Thiên Huế', 'Tỉnh Thừa Thiên Huế'),
(48,'Đà Nẵng', 'Thành phố Đà Nẵng'),
(49,'Quảng Nam', 'Tỉnh Quảng Nam'),
(51,'Quảng Ngãi', 'Tỉnh Quảng Ngãi'),
(52,'Bình Định', 'Tỉnh Bình Định'),
(54,'Phú Yên', 'Tỉnh Phú Yên'),
(56,'Khánh Hòa', 'Tỉnh Khánh Hòa'),
(58,'Ninh Thuận', 'Tỉnh Ninh Thuận'),
(60,'Bình Thuận', 'Tỉnh Bình Thuận'),
(62,'Kon Tum', 'Tỉnh Kon Tum'),
(64,'Gia Lai', 'Tỉnh Gia Lai'),
(66,'Đắk Lắk', 'Tỉnh Đắk Lắk'),
(67,'Đắk Nông', 'Tỉnh Đắk Nông'),
(68,'Lâm Đồng', 'Tỉnh Lâm Đồng'),
(70,'Bình Phước', 'Tỉnh Bình Phước'),
(72,'Tây Ninh', 'Tỉnh Tây Ninh'),
(74,'Bình Dương', 'Tỉnh Bình Dương'),
(75,'Đồng Nai', 'Tỉnh Đồng Nai'),
(77,'Bà Rịa - Vũng Tàu', 'Tỉnh Bà Rịa - Vũng Tàu'),
(79,'Hồ Chí Minh', 'Thành phố Hồ Chí Minh'),
(80,'Long An', 'Tỉnh Long An'),
(82,'Tiền Giang', 'Tỉnh Tiền Giang'),
(83,'Bến Tre', 'Tỉnh Bến Tre'),
(84,'Trà Vinh', 'Tỉnh Trà Vinh'),
(86,'Vĩnh Long', 'Tỉnh Vĩnh Long'),
(87,'Đồng Tháp', 'Tỉnh Đồng Tháp'),
(89,'An Giang', 'Tỉnh An Giang'),
(91,'Kiên Giang', 'Tỉnh Kiên Giang'),
(92,'Cần Thơ', 'Thành phố Cần Thơ'),
(93,'Hậu Giang', 'Tỉnh Hậu Giang'),
(94,'Sóc Trăng', 'Tỉnh Sóc Trăng'),
(95,'Bạc Liêu', 'Tỉnh Bạc Liêu'),
(96,'Cà Mau', 'Tỉnh Cà Mau');